name: "Ubuntu kind CI workflow"


on:
  push:
    branches: [ dev ]

jobs:


  ubuntu-latest-kind-job:
    name: "ubuntu-latest kind job"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status
    - name: "create python 2x virtual environment"
      run: sudo make create_python2_venv    
    - name: "create python 2x virtual environment auto"
      run: sudo make create_python2_venv 
    - name: "create python 3x virtual environment"
      run: sudo make create_python3_venv    
    - name: "create python 3x virtual environment auto"
      run: sudo make create_python3_venv                
    # - name: "create python 3x virtual environment - apt"
    #   run: sudo apt-get install python-virtualenv      #Package 'python-virtualenv' has no installation candidate
    # - name: "create python 3x virtual environment - easy_install"
    #   run: sudo apt-get install -yqq python-setuptools && sudo easy_install virtualenv  
      # https://docs.conda.io/en/latest/miniconda.html
    - name: "create python 3x virtual environment - conda "
      run: |
        cd tmp 
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh                 
        sha256sum Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        source ~/.bashrc
        conda list
        conda create --name venv3 python=3 -y
        conda activate venv3
    # - name: "Install k3d" 
    #   run: make install_k3d
    # - name: "Setup local cluster"
    #   run: |
    #     make create_cluster
    #     make switch_context
    #     make create_namespace               

  # ubuntu-1604-job:
  #   name: "ubuntu-16.04 minikube job"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install k3d" 
  #     run: make install_k3d    
  #   - name: "Setup local cluster"
  #     run: |
  #       make create_cluster
  #       make switch_context
  #       make create_namespace  

  # ubuntu-1804-job:
  #   name: "ubuntu-18.04 minikube job"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install k3d" 
  #     run: make install_k3d    
  #   - name: "Setup local cluster"
  #     run: |
  #       make create_cluster
  #       make switch_context
  #       make create_namespace  

  # ubuntu-2004-job:
  #   name: "ubuntu-20.04 minikube job"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "Install k3d" 
  #     run: make install_k3d    
  #   - name: "Setup local cluster"
  #     run: |
  #       make create_cluster
  #       make switch_context
  #       make create_namespace  