name: "Ubuntu kind CI workflow"


on:
  push:
    branches: [ dev ]

jobs:


  ubuntu-latest-kind-job:
    name: "ubuntu-latest kind job"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status
    - name: "create python 2x virtual environment"
      run: sudo make create_python2_venv    
    - name: "create python 2x virtual environment auto"
      run: sudo make create_python2_venv      
    # - name: "create python 3x virtual environment"
    #   run: |
    #     python -V
    #     python2 --version
    #     python3 -V
    #     python3 --version
    #     pip3 install virtualenv
    #     pip3 --version
    #     virtualenv -p $(which python3) ~venvpy3
    #     source ~venvpy3/bin/activate
    #     pip install -r requirements.txt              
    # - name: "Install k3d" 
    #   run: make install_k3d
    # - name: "Setup local cluster"
    #   run: |
    #     make create_cluster
    #     make switch_context
    #     make create_namespace               

  # ubuntu-1604-job:
  #   name: "ubuntu-16.04 minikube job"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install k3d" 
  #     run: make install_k3d    
  #   - name: "Setup local cluster"
  #     run: |
  #       make create_cluster
  #       make switch_context
  #       make create_namespace  

  # ubuntu-1804-job:
  #   name: "ubuntu-18.04 minikube job"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install k3d" 
  #     run: make install_k3d    
  #   - name: "Setup local cluster"
  #     run: |
  #       make create_cluster
  #       make switch_context
  #       make create_namespace  

  # ubuntu-2004-job:
  #   name: "ubuntu-20.04 minikube job"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "Install k3d" 
  #     run: make install_k3d    
  #   - name: "Setup local cluster"
  #     run: |
  #       make create_cluster
  #       make switch_context
  #       make create_namespace  